import Stack from "./stack";

export default {
  featured: [
    {
      title: "Travel Booking Clone",
      slug: "travel-booking-clone",
      banner: "/assets/projects/travel-booking-clone/banner.png",
      website: "https://github.com/RudraG4/Travel-Booking-Clone",
      description: "",
      shortDescription: "",
      repository: "https://github.com/RudraG4/Travel-Booking-Clone",
      stack: [Stack.react, Stack.bootstrap],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/Travel-Booking-Clone",
    },
    {
      title: "Tic-Tac-Toe",
      slug: "tic-tac-toe",
      banner: "/assets/projects/tic-tac-toe/banner.png",
      website: "https://github.com/RudraG4/Tic-Tac-Toe",
      description: "",
      shortDescription: "",
      repository: "https://github.com/RudraG4/Tic-Tac-Toe",
      stack: [Stack.react, Stack.bootstrap],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/Tic-Tac-Toe",
    },
    {
      title: "Quizzy",
      slug: "quizzy",
      banner: "/assets/projects/quizzy/banner.png",
      website: "https://github.com/RudraG4/quizzy",
      description: "",
      shortDescription: "",
      repository: "https://github.com/RudraG4/quizzy",
      stack: [Stack.react, Stack.bootstrap],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/quizzy",
    },
    {
      title: "Starwar Search",
      slug: "starwar-search",
      banner: "/assets/projects/starwar-search/banner.png",
      website: "https://github.com/RudraG4/Starwar-Search",
      description: "",
      shortDescription: "",
      repository: "https://github.com/RudraG4/Starwar-Search",
      stack: [Stack.react, Stack.bootstrap, "SWAPI"],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/Starwar-Search",
    },
  ],
  projects: [
    {
      title: "Meme Generator",
      slug: "meme-generator",
      banner: "/assets/projects/meme-generator/banner.png",
      website: "https://github.com/RudraG4/meme-generator",
      description: "A React webapp to generate Random Memes",
      shortDescription: "A React webapp to generate Random Memes",
      repository: "https://github.com/RudraG4/meme-generator",
      stack: [Stack.react],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/meme-generator",
    },
    {
      title: "Digital Business Card",
      slug: "digital-business-card",
      banner: "/assets/projects/digital-business-card/banner.png",
      website: "https://github.com/RudraG4/digital-business-card",
      description:
        "A Digital Business Card - Static page application created using ReactJS",
      shortDescription:
        "A Digital Business Card - Static page application created using ReactJS",
      repository: "https://github.com/RudraG4/digital-business-card",
      stack: [Stack.react],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/digital-business-card",
    },
    {
      title: "AirBnb Experience Clone",
      slug: "airbnb-exp-clone",
      banner: "/assets/projects/airbnb-exp-clone/banner.png",
      website: "https://github.com/RudraG4/airbnb-exp-clone",
      description:
        "An Airbnb Experirences Clone - Static page created using React",
      shortDescription:
        "An Airbnb Experirences Clone - Static page created using React",
      repository: "https://github.com/RudraG4/airbnb-exp-clone",
      stack: [Stack.react],
      dimensions: [360, 640],
      screenshots: [],
      deployment: "https://github.com/RudraG4/airbnb-exp-clone",
    },
  ],
};
